version: "3.8"
services:
  frontend:
    build:
      context: ./containers/vite
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app/frontend:cached
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USERPOLLING=true
    tty: true
    ports:
      # - 3000:3000
      - 8000:8000
    # expose:
    #   - 3000
    command: sh -c "cd /app/frontend && yarn dev"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./containers/golang/Dockerfile
    container_name: backend
    working_dir: /app
    ports:
      - 3000:3000
      # - 8000:8000
    # expose:
    #   - 8000
    tty: true
    volumes:
      - ./backend:/app/backend:cached
  nginx:
    build: ./containers/nginx
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
      - ./logs/nginx:/var/log/nginx:cached
